plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    id 'com.android.application'
    id 'com.google.gms.google-services'
}



android { signingConfigs {
    config {
    }
}
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.rapidkopainc.rapidkopa"
        minSdkVersion 26
        targetSdkVersion 33
        versionName '5'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        versionCode 5
        multiDexEnabled true
    }
    android {
        lintOptions {
            checkReleaseBuilds false

            abortOnError false
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}
android {

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.rapidkopainc.rapidkopa'
    buildFeatures {
        viewBinding true
    }
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'androidx.navigation:navigation-fragment:2.5.3'
    implementation 'androidx.navigation:navigation-ui:2.5.3'
    testImplementation 'junit:junit:4.13.2'
    //noinspection GradleCompatible
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    //noinspection GradleCompatible
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    //noinspection GradleCompatible
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.annotation:annotation:1.6.0'

    implementation 'com.google.firebase:firebase-database:20.2.2'

    implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'androidx.multidex:multidex:2.0.1'


    implementation 'com.facebook.android:audience-network-sdk:6.+'
    implementation 'com.facebook.android:facebook-android-sdk:13.0.0'
    //Flex box
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}
repositories {
    google()
    mavenCentral()
}
